#!/bin/sh

########## Memory related info ##################################
VM_PAGESIZE=`sysctl -n vm.stats.vm.v_page_size`
FREE_MEM=$((`sysctl -n vm.stats.vm.v_free_count` * $VM_PAGESIZE))
INACT_MEM=$((`sysctl -n vm.stats.vm.v_inactive_count` * $VM_PAGESIZE))
#CACHE_MEM=$((`sysctl -n vm.stats.vm.v_cache_count` * $VM_PAGESIZE))

AVAIL_MEMORY=$((`sysctl -n hw.realmem` /1024/1024))
FREE_MEMORY=$((($FREE_MEM + $INACT_MEM) /1024 /1024))

#############3 System type TrueOS #################3
# Special function for checking TrueOS version
display_trueos_version()
{
if [ -e "/etc/defaults/trueos-desktop" ] ; then
  SYSTYPE="DESKTOP"
    VER=`pkg query %v trueos-desktop`
    if [ "$VER" != "" ] ; then
    echo "TrueOS-Desktop-${1}${VER}"
  fi
else
echo "Server"
  SYSTYPE="SERVER"
  VER=`pkg query %v trueos-server`
  if [ "$VER" != "" ] ; then
    echo "TrueOS-Server-${1}${VER}"
  fi
fi
}

# Check TrueOS type again for other functions
if [ -e "/etc/defaults/trueos-desktop" ] ; then
  SYSTYPE="DESKTOP"
    VER=`pkg query %v trueos-desktop`
    if [ "$VER" != "" ] ; then
    echo "TrueOS-${SYSTYPE}-${1}${VER}"
  fi
else
echo "Server"
  SYSTYPE="SERVER"
  VER=`pkg query %v trueos-server`
  if [ "$VER" != "" ] ; then
    echo "${1}${VER}"
  fi
fi

EFICHECK=`dmesg | grep "(efifb)" | awk '{print $1}' | cut -d '(' -f 2 | cut -d ')' -f 1`

# Check to see if BIOS/EFI is used as the bootloader type
if [ $EFICHECK = "efifb"  ] ; then
    export LOADERTYPE=EFI
  else
    export LOADERTYPE=BIOS
fi

# Check to see if Grub is used as the bootloader
if [ -f /etc/grub/grub.cfg ] ; then
    export BOOTLOADER=GRUB
  else
    export BOOTLOADER=BSD
fi

display_trueos_banner()
{
echo "  ______                   ____  _____"
echo " /_  __/______  _____     / __ \/ ___/ "
echo "  / / / ___/ / / / _ \   / / / /\__ \ "
echo " / / / /  / /_/ /  __/  / /_/ /___/ / "
echo "/_/ /_/   \__,_/\___/   \____//____/  "
echo ""                                      
}

# Display pkg info for Desktop
display_pkg_version()
{
  VER=`pkg query %v $2`

  if [ "$VER" != "" ] ; then
    echo "${1}${VER}"
  fi
}

# Display pkg_info

display_trueos_banner 

echo "General info:"
echo "       Host:...............`hostname`"
echo "       User:...............`whoami`"
echo "       Uptime:.............`uptime | awk '{sub(/^.* up +/,"");sub(/, *[0-9]+ users.*/,"");print}'`"
echo "       FreeBSD kernel ver:.`uname -r`"
echo "       FreeBSD world ver:..`freebsd-version`"
echo "       FreeBSD git branch:.`uname -a | awk '{print $7}' | cut -d '(' -f 2 | cut -d ')' -f1`"
echo "       FreeBSD git rev:....`uname -a | awk '{print $7}' | cut -d '(' -f 1`"
echo "       TrueOS ver:.........`display_trueos_version`"
echo "       Arch:...............`uname -m`"
echo "       Kernel ident:.......`uname -i`"
echo "       Bootloader:.........`echo $BOOTLOADER`"
echo "       Bootloader type:....`echo $LOADERTYPE`"
echo "       CPU:................`sysctl -n hw.model`"
echo "       CPU cores:..........`sysctl -n kern.smp.cpus`"
echo "       Memory (free/avail):${FREE_MEMORY} / ${AVAIL_MEMORY} Mb"
echo "       Package set:........`cat /usr/local/etc/trueos.conf 2>/dev/null | grep '^[[:space:]]*PACKAGE_SET: ' | sed 's|[[:space:]]*PACKAGE_SET: ||g'`"

if [ "$SYSTYPE" = "DESKTOP" ]; then 
  echo "       Desktop environment:`sed -n 2p /var/db/pcdm/lastlogin`"
  echo "       X11 Driver:.........`awk '{if (sub(/^.*Loading.*modules\/drivers\//,"")) { printf "%s ",$0 } }END{print "";}'  < /var/log/Xorg.0.log`"

  echo ""
  echo "Graphics HW information:"
  echo "       "`glxinfo | grep "direct rendering"`
  echo "       "`glxinfo | grep 'OpenGL renderer string'`

  echo ""
  echo "Sound HW information:"
  echo "       "`cat /dev/sndstat | grep default`

  echo ""
  echo "Wireless HW information:"
  echo "       "`sysctl -b net.wlan.devices`
fi

echo ""
echo "Network IPV4 address: "
ifconfig | grep "inet " |  awk '{ print "       "$2 }'
echo ""
echo "Network IPv6 address: "
ifconfig | grep "inet6" |  awk '{ print "	"$2 }'
